const https = require('https');
const fs = require('fs');
const path = require('path');
const express = require('express');
const os = require('os');
const { ExpressPeerServer } = require('peer');

const app = express();
const PORT = 3000;

// SSL certificates generated by mkcert
const sslOptions = {
  key: fs.readFileSync(path.join(__dirname, 'certs', 'key.pem')),
  cert: fs.readFileSync(path.join(__dirname, 'certs', 'cert.pem')),
};

// Serve static files from /public
app.use(express.static(path.join(__dirname, 'public')));

// Create HTTPS server
const server = https.createServer(sslOptions, app);

// ── Local PeerJS signaling server ──────────────────────────────────
const peerServer = ExpressPeerServer(server, {
  debug: true,
  path: '/',           // routes will be at /peerjs/*
  allow_discovery: false,
});
app.use('/peerjs', peerServer);

peerServer.on('connection', (client) => {
  console.log(`  [PeerJS] peer connected: ${client.getId()}`);
});
peerServer.on('disconnect', (client) => {
  console.log(`  [PeerJS] peer disconnected: ${client.getId()}`);
});
// ───────────────────────────────────────────────────────────────────

server.listen(PORT, '0.0.0.0', () => {
  console.log('\n🏠 HomeCast HTTPS Server is running!\n');
  console.log(`  Local:   https://localhost:${PORT}`);

  // Print all local network URLs
  const interfaces = os.networkInterfaces();
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      if (iface.family === 'IPv4' && !iface.internal) {
        console.log(`  Network: https://${iface.address}:${PORT}`);
      }
    }
  }
  console.log(`\n  PeerJS signaling: /peerjs\n`);
});
